### ISSUE TITLE
Don't require `primaryKey`

### ISSUE THREAD

**Issue by nathanboktae** [benschulz/ko-grid#2]
Why is a `primaryKey` needed? why can't I just render some columns?

With Griddle for example, if you have an array of objects, [that's all you need](http://griddlegriddle.github.io/Griddle/quickstart.html). You should strive to simplify this API.

**Comment by benschulz** [comment]
> Why is a primaryKey needed? why can't I just render some columns?

Primary keys enable use of hashes as a data model. E.g. the selection extension stores the selected rows in a hash (by primary key). Selecting/deselecting and checking whether a row is selected are all O(1) operations. Without a primary key deselecting and checking would both be O(n).

> With Griddle for example, if you have an array of objects, that's all you need. You should strive to simplify this API.

While I don't see any way of removing primary keys, `primaryKey` could default to `'id'` and a utility method for constructing a data source could be added. Said method would be given a set of objects and each object would be given a generated `id` (which, however, would modify the object).

**Comment by nathanboktae** [comment]
> E.g. the selection extension stores the selected rows in a hash (by primary key). Selecting/deselecting and checking whether a row is selected are all O(1) operations. 

Just put them in an array. Who cares if it's linear it is in memory javascript. Your killing a use case and creating a convoluted API for a performance problem that doesn't exist.

The fact that I've been the first person to file an issue in months despite great exapmles, tests, and docs hint towards others that have seen the design problems and moves on.

**Comment by benschulz** [comment]
> Just put them in an array. Who cares if it's linear it is in memory javascript.

Short answer: The performance issue _does_ exist. That's why a `primaryKey` is required. 

Long answer: This is a turtles-all-the-way-down knockout component. That makes it very flexible and easily extensible (which were two design goals). It also means that the grid's DOM is assembled entirely via JavaScript (`Node.appendChild`, etc.), which is incredibly slow. The `primaryKey` lets the implementation cut down on DOM manipulation and thus increase performance dramatically. (For instance, sorting the grid simply reorders the `tr`s rather than updating every single `td`'s content.)

> Your killing a use case and creating a convoluted API for a performance problem that doesn't exist.

I'm not killing a use case, I'm enabling one. Admittedly, simpler use cases are getting a little harder as a side effect.

> The fact that I've been the first person to file an issue in months despite great exapmles, tests, and docs hint towards others that have seen the design problems and moves on.

Your feedback is appreciated. However, dropping the `primaryKey` requirement would require a new architecture and I don't think it would be as flexible and extensible as the current one.

**Comment by nathanboktae** [comment]
> The primaryKey lets the implementation cut down on DOM manipulation and thus increase performance dramatically.

Knockout 3.0 or 3.2 introduced [more granular array change notifications](http://blog.stevensanderson.com/2013/10/08/knockout-3-0-release-candidate-available/) as well as there are an index repeat bindings available. Either way this has nothing to do whether the data has a primary key or not. It's just deltas on an array.

You are killing a use case. You force IDs to be strings, while most IDs from a typical REST API will be an integer.

I have never found another grid that has such restrictions on the data it can present. So somehow everyone else before you has figured this out - including [KoGrid](https://github.com/Knockout-Contrib/KoGrid) and [ng-grid](https://github.com/angular-ui/ui-grid) that also use DOM-based templating.

**Comment by benschulz** [comment]
> Knockout 3.0 or 3.2 introduced more granular array change notifications as well as there are an index repeat bindings available. Either way this has nothing to do whether the data has a primary key or not. It's just deltas on an array.

That assumes deltas come about on the client side. What happens when you get the latest data from the server? Then computing the delta becomes O(ndp) where p is the property count – plus a pretty healthy constant factor for cache thrashing.

> You are killing a use case. You force IDs to be strings, while most IDs from a typical REST API will be an integer.

Again; I'd argue it's enabling use cases. Many APIs provide GUIDs/UUIDs. No matter what your ID type is, there exists a homomorphism between it and strings.

I concede that working with APIs based on integer IDs is cumberstone at the moment. One needs to convert those integer IDs to strings and it's unncessary. I suppose the `primaryKey` property could also be specified as a function `f: entry → string`. Then `f` could to the conversion on-the-fly.

**Comment by nathanboktae** [comment]
> That assumes deltas come about on the client side. What happens when you get the latest data from the server? Then computing the delta becomes O(ndp) where p is the property count – plus a pretty healthy constant factor for cache thrashing.

That is not the grid's concern. You're coupling that problem into the grid and violating the single responsibility principle. Put it in `ko-grid-data-source`'s RemoteDataSource and require an ID there.

**Comment by benschulz** [comment]
I'd be willing to have data sources expose their `idSelector`. However, that would include the `ClientSideDataSource` whose `replaceEntries` method is equally affected by the diff-issue. This would be a convenience change, so one does not have to specify the `primaryKey` twice. Not what you are looking for, I believe, but at least doable within the current architecture.
